---
- name: Install OpenSSH
  package:
    name: openssh-server

- name: Install OpenSSH Config
  tags: [openssh]
  template:
    src: sshd_config.j2
    dest: "{{ openssh_sshd_config_file }}"
    mode: "0644"
  notify: restart sshd
