---
- name: Install OpenSSH
  tags: [sshd]
  package:
    name: openssh-server

- name: Install OpenSSH Config
  tags: [sshd]
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_file }}"
    mode: "0644"
    validate: sshd -t -f %s
  notify: restart sshd
